USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS "dev_wh"
    WITH WAREHOUSE_SIZE = 'X-Small'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for learning Snowflake';

SHOW WAREHOUSES;

CREATE DATABASE IF NOT EXISTS movies_db
    COMMENT = 'Database for movies DLT';

SHOW DATABASES;

CREATE SCHEMA IF NOT EXISTS movies_db.staging
    COMMENT = 'Schema for movies DLT';

SHOW SCHEMAS IN DATABASE movies_db;

DESCRIBE DATABASE movies_db;

