SHOW DATABASES;

-- SWITCH TO APPROPRIATE ROLE
USE ROLE SYSADMIN;

-- SETUP DATABASE FOR DLT CSV DATA INGESTION
CREATE DATABASE IF NOT EXISTS "06_MOVIES_DB";
USE DATABASE "06_MOVIES_DB";

-- SETUP STAGING SCHEMA
CREATE SCHEMA IF NOT EXISTS "staging";

-- ALTERNATIVE: USE "FULLY_QUALIFIED_NAMES" PARAMETER
-- CREATE SCHEMA IF NOT EXISTS "06_MOVIES_DB"."staging";




-- CLEANUP
DROP SCHEMA IF EXISTS "staging" CASCADE;
DROP DATABASE IF EXISTS "06_MOVIES_DB" CASCADE;