-- SWITCH TO APPROPRIATE ROLE
USE ROLE USERADMIN;

-- CREATE ROLE FOR DLT CSV DATA INGESTION
CREATE USER IF NOT EXISTS "extract_loader" 
    PASSWORD="1234" 
    DEFAULT_WAREHOUSE="COMPUTE_WH";

-- CREATE ROLE FOR DLT CSV DATA INGESTION
CREATE ROLE IF NOT EXISTS "movies_dlt_role";


-- CLEANUP
DROP ROLE IF EXISTS "movies_dlt_role";
DROP USER IF EXISTS "extract_loader";