USE ROLE SYSADMIN;

SELECT CURRENT_ROLE();

SELECT CURRENT_USER();

CREATE WAREHOUSE IF NOT EXISTS "05_ice_cream_wh"
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = "Warehouse for ice cream shop";

SHOW WAREHOUSES;

USE WAREHOUSE "05_ice_cream_wh";