USE ROLE SYSADMIN;

SELECT CURRENT_ROLE();

SELECT CURRENT_USER();

CREATE WAREHOUSE IF NOT EXISTS dev_wh
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for learning Snowflake';

SHOW WAREHOUSES;

USE WAREHOUSE dev_wh;