SHOW WAREHOUSES;

CREATE WAREHOUSE demo_wh
WITH
WAREHOUSE_SIZE = 'X-Small'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Demo warehouse created through worksheet';

SHOW WAREHOUSES;

ALTER WAREHOUSE demo_wh
SET MAX_CLUSTER_COUNT = 3;

